### ISSUE TITLE
Vendor prefixing?

### ISSUE THREAD

**Issue by doctyper** [chriskjaer/stilr#6]
Hi, loving Stilr so far. Can your recommend an approach to vendor prefix values in development / hot-load mode? Autoprefixer works great on the server side but it seems to have compatibility issues being imported into Webpack.

**Comment by chriskjaer** [comment]
Yeah, there's a trick to get Autoprefixer working with webpack. In your webpack config you have to add:
```
  node: {
    fs: 'empty'
  }
```

After that you're able to use autoprefixer on the client as you would on the server. I'll add it to the documentation.

**Comment by chriskjaer** [comment]
I've added an entry to the readme about this and how to use autoprefixer in development.
